name: Auto Approve PRs for /dev 

on:
  pull_request:
    types: [opened,synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | xargs)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if all files are in /dev
        id: verify
        run: |
          BAD_FILE=0
          for file in $CHANGED_FILES; do
            if [[ "$file" != dev/* ]]; then
              echo "Found non-dev file: $file"
              BAD_FILE=1
              break
            fi
          done
          echo "SELF_APPROVE=$([ $BAD_FILE -eq 0 ] && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Auto approve PR
        if: env.SELF_APPROVE == 'true'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
